### ISSUE TITLE
Add gitignore from gitignore.io

### ISSUE THREAD

**Issue by zrma** [namonak/golang_of_pyrasis#1]
https://github.com/namonak/golang_of_pyrasis/blob/a982ff862ac1520d34a16570790f3b0985a56c13/.gitignore#L12

> ref: https://gitignore.io/api/go,vim,linux,windows,jetbrains,visualstudiocode

**Comment by namonak** [comment]
Updated .gitignore as follows.
- bdfe17d67119bc06b1a031a0a05ce05bb59acaa0

Thank you for your advice! :)
