### ISSUE TITLE
변수명 명시하기

### ISSUE THREAD

**Issue by zrma** [namonak/golang_of_pyrasis#2]
https://github.com/namonak/golang_of_pyrasis/blob/f61cf2c3bf6c273204d16ac6ffadec9c706305eb/src/easy_example/easy_example.go#L7

```
for i := 1; i <= 100; i++ {
	fizz, buzz := i % 3 == 0, i % 5 == 0
	switch {
	case fizz && buzz:
		fmt.Println("FizzBuzz")
	case fizz:
		fmt.Println("Fizz")
	case buzz:
		fmt.Println("Buzz")
	default:
		fmt.Println(i)
	}
}
```

이런 건 어떨까?

**Comment by namonak** [comment]
수정해 주신 코드가 이전 코드보다 직관적이고 가독성도 좋네요.
수정 후 적용하였습니다. 좋은 지적 감사합니다! 
- bd02851d1c11c6c171c2411fa41d839cc445edb6
