### ISSUE TITLE
문자열 상수 정의

### ISSUE THREAD

**Issue by zrma** [namonak/golang_of_pyrasis#3]
https://github.com/namonak/golang_of_pyrasis/blob/f61cf2c3bf6c273204d16ac6ffadec9c706305eb/src/easy_example/easy_example.go#L9

```
const (
	fizz = "Fizz"
	buzz = "Buzz"
)

for i := 1; i <= 100; i++ {
	switch {
	case (i%3 == 0) && (i%5 == 0):
		fmt.Println("%s%s", fizz, buzz)
	case i%3 == 0:
		fmt.Println("%s", fizz)
	case i%5 == 0:
		fmt.Println("%s", buzz)
	default:
		fmt.Println(i)
	}
}
```

**Comment by namonak** [comment]
코드에서 문자열 상수 사용하도록 수정하였습니다.
형식 지정자 사용을 위해서 fmt.Println 함수를 fmt.Printf 로 대체하였습니다.
- 0751a70fcc1344af004ca2b12573bdf1db106de3
