### ISSUE TITLE
커밋 전 하면 좋은 것

### ISSUE THREAD

**Issue by zrma** [namonak/golang_of_pyrasis#4]
https://github.com/namonak/golang_of_pyrasis/blob/0751a70fcc1344af004ca2b12573bdf1db106de3/src/easy_example/easy_example.go#L12

```
$ go fmt ./...
$ go vet ./...
```

용도는 각각 확인해 볼 것.

**Comment by namonak** [comment]
go fmt :  미리 정의된 소스코드 레이아웃을 Go 소스 코드에 자동으로 적용해 줌. 
go vet : 코드상에서 일반적으로 발생할 수 있는 에러를 검사해 줌.
./... : 현재 디렉토리를 기준으로 하위 디렉토리 까지를 포함하는 GO 컨벤션?? 맞나요??
